### PR TITLE
Project to make most items have descriptions

### PR DESCRIPTION
**Pull request by JohnBigless**
TODO - Fill in `desc` and `desc_extended` for the following items.
List provided by PigeonLord.
CLOTHING AND ARMOR
- [x] Bandana
- [x] Priest's garb
- [x] medical backpack
- [x] Most backpacks/satchels/duffelbags not having descriptions
- [x] All Boots use the same description
- [x] All Gloves use the same description
- [x] Beaver Hat has shitty desc
- [x] Cult hood has an extended desc, but no desc
- [x] Hardhat has an extended desc, but no desc
- [x] HoP and HoS hats
- [x] Winter Hood and Hoodie Hood
- [x] Bandage Mask
- [x] Cape
- [x] Cloak has an extended desc, but no desc
- [x] Bone Armor
- [x] Carbon Armor
- [x] All types of Cult Robes
- [x] Ash Drake Armor
- [x] Explorer's Suit
- [x] Gladiator Armor
- [x] All Knights Armors
- [x] Leather Armor
- [x] All armor in molded.dm
- [x] prototype carbon fibre armor
- [x] Blacksmith Apron has an extended desc, but no desc. Also Apron is spelled wrong.
- [x] Hoodie
- [x] HoS coat
- [x] Labcoat
- [x] Winter Coat
- [x] Bomber's Coat has no desc_extended
- [x] Engineering hardsuit
- [x] Mining Hardsuits
- [x] All Syndicate Hardsuits
- [x] H.E.K. hazard hardsuit
- [x] All pants except Syndicate Pants use the same description
- [x] All Skirts use the same description
- [x] All Blouses have no desc
- [x] All Shirts have no desc
- [x] All Underwear has no desc
- [x] Stealth Suit has no desc_extended
- [x] Pretty much everything in the clothing/uniform folder

MEDICINE AND FOOD
- [x] Most Food either has no desc or no desc extended
- [x] All medicines has the same description
- [x] All sprays have no desc
- [x] Vials, Flasks and beaker have no desc

MISC
- [x] All Data Disks have no desc
- [x] The Bike Horn has no extended desc
- [x] All Instruments have no desc
- [x] All powercells have no extended desc
- [x] Soapstone has no extended desc

WEAPONS
- [x] Grenades have no extended desc
- [x] Dragon and SVD Dragunov has no extended desc
- [x] All Laser Rifles have no desc
- [x] Chronogun (What the fuck is a Chronogun, anyway)
- [x] Freeze Ray
- [x] Nut Gun
- [x] Hybrid Laser Gun
- [x] The .50 Sniper has no extended desc
- [x] Syringe Rifle
- [x] 9mm SMP
- [x] .40 Nanotech SMG
- [x] Silent Syndicate SMG
- [x] .22LR Wasp SMG has no extended desc
- [x] Lever Action Shotgun has no extended desc
- [x] 12g Civilian Shotgun has no extended desc
- [x] Big Game Revolver has no extended desc
- [x] 44 Commander Autorevolver has no extended desc
- [x] 12 Gauge Boomstick has no extended desc
- [x] .44 Space Detective Revolver has no extended desc
- [x] .38 Special Revolver has no extended desc
- [x] Traitor Revolver has no extended desc
- [x] All Staffs (Staves?) have no extended desc

STUFF FEATURED IN PR #43 
- [x] Headset
- [x] Protective helmet
- [x] Ski mask
- [x] Ushanka
- [x] Padded kevlar sec armor
- [x] Syndicate pants and shirt
- [x] Pinpointers
- [x] First aid kits
- [x] Storage pouches
- [x] Captain's laser pistol
- [x] Flight control console

**We're done here, for now.**

### CODE REVIEW

**Comment by JohnBigless** [comment]
@PigeonLord

**Comment by PigeonLord** [comment]
Added Laser Rifle Descs
Added Chronogun Desc
Added Hybrid Laser Gun Desc
Added Freeze Ray Desc
Added Nut Gun Desc
Added Staffs Descs

**Comment by PigeonLord** [comment]
Added Dragon and SVD Dragunov descs
Added 50 Sniper Descs
Added Descs for all SMGs
Added Descs for all Shotguns
Added Descs for all Revolvers
Added Grenade Desc

**Comment by PigeonLord** [comment]
Added a Desc for Molded Armors
Added a Desc for Knights Armors
Added a Desc for Carbon Armor
Added a Desc for Gladiator Armor
Added a Desc for Leather Armor
Added a Desc for Cult Robes
Added a Desc for Prototype Carbon armor
Added a Desc for Bone Armor

**Comment by PigeonLord** [comment]
Added descs for Medicines
Added descs for Sprays
Added Descs for Mining Bags
Added Descs Flasks, Vials, Beakers and Potion bottles
Added Desc for Pill bottles

**Comment by PigeonLord** [comment]
Added all Hardsuit Descs

**Comment by PigeonLord** [comment]
Did the underwear and the undertops

**Comment by PigeonLord** [comment]
Added descs for shirt and pants

**Comment by PigeonLord** [comment]
Wrote descs for all things in the uniform dm

**Comment by BurgerLUA** [comment]
Is this good to merge?

**Comment by PigeonLord** [comment]
Good to merge

**Pull request merged**
