### PR TITLE
you know what fuck you *ungoblins your horde*

### PR DESCRIPTION
**Pull request by Stalkeros2**
# What this PR does
comments goblin horde

# Why it should be added to the game
fuck you

### CODE REVIEW

**Comment by VVivec** [comment]
Preach queen

**Comment by BurgerLUA** [comment]
I need to know the context behind this PR.

**Comment by jjpark-kb** [comment]
> I need to know the context behind this PR.

Goblin horde type is picked too frequently, pretty sure that is the context. I don't agree with disabling it because people _**pick**_ it.

**Comment by Stalkeros2** [comment]
That's a joke.

**Comment by Stalkeros2** [comment]
But yeah the reason is that goblin horde is too rewarding for the difficulty it has.

**Comment by BurgerLUA** [comment]
This PR will be merged when we do the wipe. Goblin horde should be an event rather than a gamemode.

**Review by BurgerLUA — APPROVED** [review]

**Pull request merged**
