### PR TITLE
death

### PR DESCRIPTION
**Pull request by Harrivchaw**
# What this PR does
adds cursed neko lingerie
image
# Why it should be added to the game
you tell me

### CODE REVIEW

**Comment by Stalkeros2** [comment]
HAHAHAHAHAHAHAHAHA

**Comment by jc-denthead** [comment]
NONONONONONONONONONO

**Comment by Insane-Jimmy** [comment]
im gonna go convulse on the floor now

**Comment by FancyCyclops** [comment]
YOU DANDY FUCK

**Review by FancyCyclops — APPROVED** [review]
All in all, looks fine.

Won't really break any balances.

Might be light.

All I know is that it now needs somewhere to be vended from.

**Review by BurgerLUA — APPROVED** [review]
this is a mistake

**Pull request merged**
