### PR TITLE
Crafting components

### PR DESCRIPTION
**Pull request by Stalkeros2**
# What this PR does
Adds crafting components and some spawnable, mineable metals with alloys for future use. This PR might include crafting recipes later, but for now there'll be only components, new metals, alloys and a single placeholder recipe.

# Why it should be added to the game
> mfw RPG without crafting smh.

### CODE REVIEW

**Comment by Stalkeros2** [comment]
Damn I forgot about duplicate definitions brb.

**Comment by Stalkeros2** [comment]
I am writing this note in case someone else would want to continue *actually* improving crafting. If not, then I'll do the rest after I'm done with most of my IRL stuff.

Okay, so here's the overall plan on what to presumably do with the rest of the stuff:
All aluminium and steel alloys should be available on station via some vendor;
Nickel alloys should be craftable on station after some messing around with the available stuff on the station;
Titanium alloys should be either lootable from chests or from mobs;
Plasteels should be boss drop;
All of the synthcloths should be available on station: simple one is buyable, others are craftable;
Devilstrand should be lavaland-only loot, variations should be craftable;
Durathread should be boss-only loot, variations should be craftable.
Polymer Alpha should be buyable on station;
Polymers Beta and Gamma should be craftable (Beta from Alpha and some bullshit and Gamma from Beta and some bullshit);
Polymer Epsilon is chest loot/crate loot;
Polymer Omega is boss-only loot.
As for the misc crafting stuff:
Scrap should be easily craftable from most, if not any equipment via disassembling;
Same for electronics;
Duct tape should be bought from engi vendor;
Air regulators should be crafted.

**Comment by Stalkeros2** [comment]
Alright, the barebones part of it's done now. I'll add more specific recipes later, as I need some time to assemble them.

**Review by BurgerLUA — DISMISSED** [review]

**Comment by BurgerLUA** [comment]
Is this still being worked on?

**Comment by BurgerLUA** [comment]
Also conflicts.

**Comment by Stalkeros2** [comment]
Alright, done.

**Review by BurgerLUA — APPROVED** [review]

**Pull request merged**
