### PR TITLE
ENDLESS REVOLVERS, A COMEDY OF ERRORS

### PR DESCRIPTION
**Pull request by FancyCyclops**
# What this PR does
sets up the base for item creators by lazily copying quivercode
Also sets up the base for temporary weapons in a similar way.
TO DO: prevent throwing and storage to not give admins heart attacks
# Why it should be added to the game
Perfect weapon for those that hate reloading in a battle.

### CODE REVIEW

**Comment by FancyCyclops** [comment]
TODO: WHY THE FUCK DO THE TEMP REVOLVERS STILL SELL FOR A PRICE HIGHER THAN 1/0

WHAT THE SHIT? WHY THE FUCK? WHY THIS?

**Comment by FancyCyclops** [comment]
I found a better solution than all this jank, but it's going to take some time to clean up. Please wait warmly.

**Review by Stalkeros2 — APPROVED** [review]
baste :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Review by Stalkeros2 — APPROVED** [review]
basd

**Pull request merged**
