### PR TITLE
The Official Mercenary PR

### PR DESCRIPTION
**Pull request by BurgerLUA**
# What this PR does

- Adds Mercenaries as an antagonist type. Mercenaries spawn on all maps except Lavaland. They spawn with all their equipment on them, which means they cannot purchase additional equipment and must find everything on the battlefield.
- Mercenaries are given a random outfit on spawn from a pool of 4 outfits. Duplicate outfits cannot occur.
- Mercenaries are given a random codename on spawn from a pool of random codenames. Duplicate codenames cannot occur.
- Adds 4 new weapons (FAMAS Ripoff, Browning Ripoff, Galil Ripoff, Black Desert Eagle Ripoff)
- Adds 2 new ammo types: .40 tranq round (similar to the existing tranq round) and .50 heartbreaker ammo (deals a mix of increased slash, brute, and pierce damage)
- Adds a new fulton pack mechanic. Players can now fulton almost everything to be sold to them for credits. Antags who fulton players who owe taxes are forced to pay taxes, with 25% of the profits going to the antag.
- Restrictions on fultoning living beings: The living being must be horizontal and alive, and they must not share the same IFF tag as the person doing the fultoning.
- Any credits that antags gain is stored to the player's savefile and can be redeemed at the front desk.

# Why it should be added to the game

New content good.

## Possible Outfits

image

image

image

image

## New Weapons

image

## Todo

- [x] Make sure that antags save their credits on gain.
- [x] Make sure that only 25% of the currency gained from tax is given to the antag.
- [x] Add headset channel for mercs.
- [x] Confirm that Mercs can spawn in.
- [x] Add a 50% damage reduction to Mercs, unless they kill someone, which then is reduced to 0% damage reduction.
- [x] Add instructions to Mercs.
- [x] Add unique CQC for merc.

### CODE REVIEW

**Comment by Stalkeros2** [comment]
Nice.

**Comment by Mouseofthecake** [comment]
hey so who exactly will be able to harm the bounty hunters? only ppl who are overdue on taxes, or all nt mercs?

**Comment by BurgerLUA** [comment]
> hey so who exactly will be able to harm the bounty hunters? only ppl who are overdue on taxes, or all nt mercs?

Everyone.

**Comment by BurgerLUA** [comment]
Some additional changes in this PR:

- Fixes radios not working as intended. The previous radio PR kinda broke radios in a way but fixed a majority of the features. Those features have been fixed.
- The CQC framework has some extra stuff added to it to make it better. Eventually I will expand it.
- Varedit has been fixed with respect to changing vars to 0.
- A "Add Loadout" verb has been added to debug. It allows you to test outfits.
- A new feature called "partial tax" has been added that allows you to pay your taxes partially if you have the funds for it. Note that paying taxes partially considers you still overdue.
- Syndicates can now talk on syndicate radio with ,t.
- Credits gained by antags are stored in your global save file. Currently there is no way to redeem it, yet, but it can still be tracked.
- A limit on antags has been added. Currently there are 2 slots plus 0.2 slots for every player on the server for antags.
- A special message displays to ghosts when a player kills another player.
- The lights do not go out when antags invade the station.

**Pull request merged**
