### PR TITLE
The Annihilator Addition

### PR DESCRIPTION
**Pull request by NzzyFk**
# What this PR does
Adds the M1919 Annihilator, based off of the early variants of the Thompson SMG. It comes with a 100 round drum magazine, firing .45 ACP caliber bullets. 

# Why it should be added to the game
It's a fun and iconic gun.

### CODE REVIEW

**Comment by NzzyFk** [comment]
something to be noted, when you pick up the tommygun or the drum, some red text pops up. im assuming its from the qdel bullshit thingamajig i dont understand.

**Comment by Moltovz** [comment]
is it going to be as broken as the AN-94?

**Comment by NzzyFk** [comment]
Likely not, it's a skill creep kinda gun. I set the inaccuracy to 1.5, but it does give you overwhelming supressive fire in exchange. It bcomes somewhat precise at skill level 50 ranged and level 50 precision I think.

**Comment by NzzyFk** [comment]
Ping me on discord if you wanna show me it's borked, I can just bump up the inaccuracy even more.

**Comment by NzzyFk** [comment]
https://dw.convertfiles.com/files/0125082001626762247/2021-07-20%2013-17-38.mp4

test run video of thompson at skill 0, 50 and 100 ranged and precision. also comparison to the sol-15 battle rifle.

**Review by Stalkeros2 — APPROVED** [review]
LETS GOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Pull request merged**
