### PR TITLE
Musket Bag

### PR DESCRIPTION
**Pull request by IjNebula**
# What this PR does
Adds a musket bag that holds up to 80 .62 powder charges, and is worn in the belt slot
Gives the premium restocker the ability to fill the musket bag with charges
Gives the musket bag to ranged skeleton crew*
Adds the musket bag to the costume vendor
*Does NOT update mob AI to use bandolier-esque items

Also included
-Premium powder charges
-Faster flintlock loading with premium powder charges
-Changes to bullet_time system so it can apply different times for different bullets
-Hotfix for plasma cutter because it was causing me compiling issues

# Why it should be added to the game
Please refer to the suggestion "Ammo bag for musket ammo" in the official burgerstation discord server

### CODE REVIEW

**Comment by BurgerLUA** [comment]
Will try to merge this in the next major update.

I was hesitant to merge this because I wanted to make a new type of object that has universal functionality (12 gauge belt, arrows, quivers) but I kept forgetting to do that.

**Comment by IjNebula** [comment]
It's extremely broken right now, I'm gonna make a bunch of reverts so that it's just the musket bag and premium flintlock ammo.

**Comment by IjNebula** [comment]
It's ready. I procrastinated a lot and experienced a lot of issues with github causing me to lose progress, but it's ready

**Comment by IjNebula** [comment]
> There seems to be something wrong because it's trying to add old ancient files that have been deleted.

Yeah, it seemed a little suspicious when the PR wanted to add 500 other things that weren't the musket bag and were supposed to have been copied from the master branch.

Gonna go ahead and cut everything in the PR except for the musket bag related things.

**Comment by IjNebula** [comment]
Okay, so I downloaded a new copy of burgerstation, went through my files and only added the ones that I had personally changed and wanted to push, then overwrote my old copy of burgerstation with the new copy. 
HOPEFULLY that got rid of the old files that were trying to sneak their way back.

**Comment by Gboster-0** [comment]
> Okay, so I downloaded a new copy of burgerstation, went through my files and only added the ones that I had personally changed and wanted to push, then overwrote my old copy of burgerstation with the new copy. HOPEFULLY that got rid of the old files that were trying to sneak their way back.

nope

**Comment by IjNebula** [comment]
> > Okay, so I downloaded a new copy of burgerstation, went through my files and only added the ones that I had personally changed and wanted to push, then overwrote my old copy of burgerstation with the new copy. HOPEFULLY that got rid of the old files that were trying to sneak their way back.
> 
> nope

Wdym?

**Comment by IjNebula** [comment]
Actually nevermind I'm just gonna do what I should have done a looooong time ago

**Pull request closed without merging**
