### PR TITLE
Adds new sanity dealing melee weapon, and reskinned sunglasses with slight armor changes

### PR DESCRIPTION
**Pull request by muzcl**
# What this PR does
Adds a new sanity dealing melee weapon, the Dismembered Hand. Obtainable by butchering Dick Kickem, this has an incredibly high attack delay, but deals lots of damage on attack, and plays Duke Nukem 3D voicelines randomly when it does. Also adds reskinned sunglasses that matches the ones Dick wears, obtainable by butchering him too. They give different armor stats in favor of physical resistance, but give decent magic vulnerability.

# Why it should be added to the game
There are no current sanity dealing melee weapons I know of, it playing Duke Nukem voicelines is very funny, and the sunglasses are so there's another viable option for glasses (also for cosplay).

Credits to nzzy on discord for the spritework.

https://github.com/BurgerLUA/burgerstation/assets/109846546/c3463b2c-4435-435f-a0c7-77fd6882c8b1

### CODE REVIEW

**Comment by muzcl** [comment]
this should hopefully be funnier and fit better than the previous iteration

**Comment by muzcl** [comment]
I'll remove the meme deathgasp because its not really relevant, and give the glasses an actual use besides cosplay

**Comment by muzcl** [comment]
I should probably remove some of the voice lines as well, but I'll do it if Burger or another reviewer asks.

**Comment by BurgerLUA** [comment]
> I should probably remove some of the voice lines as well, but I'll do it if Burger or another reviewer asks.

References are fine but direct references, such as ripped voicelines, are not good unless they're incredibly rare (see: some emote variations).

**Comment by muzcl** [comment]
> References are fine but direct references, such as ripped voicelines, are not good unless they're incredibly rare (see: some emote variations).

Fair enough. I'll replace it with a generic hit sound.

**Comment by muzcl** [comment]
alright, i replaced it with a generic heavy punch sound and lowered its damage and attackdelay to reflect that

**Review by BurgerLUA — APPROVED** [review]

**Pull request merged**
