### PR TITLE
Botany changes

### PR DESCRIPTION
**Pull request by Moltovz**
# What this PR does
- makes plants grow slower (mainly on soil)
- Adds one yield every 50 points in botany instead of every "25" it may seem major, dont moan about it, you get enough from one harvest anyway

# Why it should be added to the game
Muh plants

### CODE REVIEW

**Comment by Moltovz** [comment]
closing this, it doesnt really seem needed with the new caps to botany (maybe)

**Comment by Moltovz** [comment]
know what, we need this 
image

**Comment by drakewill-CRL** [comment]
If dudes are gonna insist on crashing the server with LETTUCE, the yield change is a good idea.
You should probably test the 3 speed nerfs you did on local to see how much longer/harder it makes plants to grow.
Any one of them was probably OK. All 3 might put botany back to 'plants die before you can harvest them'

**Comment by BurgerLUA** [comment]
Is there currently still a problem with growing spam?

**Review by BurgerLUA — APPROVED** [review]
Seems good.

**Pull request merged**
