### PR TITLE
Additional off-type content

### PR DESCRIPTION
**Pull request by drakewill-CRL**
# What this PR does
* 3 new spellgems! 2 are boss loot, 1 is found in the prize vendor.
* 7+ SpellSwap mag enhancers! Scattered across the world as boss loot. (Each boss has 2 possible drops)
** Your current bullets becomes spells, when they're fired off they're gone. This also doesn't persist between station rounds, so use these carefully!
* Regen enchantment tweak/fix. New bullets now go into the BOTTOM of the mag, not the TOP.
* Cursed Canine tweak: Should no longer level magic stats via ranged weapon. Still uses them for determining damage, though.

# Why it should be added to the game
Get more feedback on if bullet-gems are too good, or just shotgun-gems.
An alternative path for magic-guns by letting any gun shoot any (of the 7 available) spell temporarily, instead of Cursed Canine style fixed-spell guns.
Set the Cursed Canine to not be an easy magic-stat grinding item. Otherwise it remains the same,

### CODE REVIEW

**Comment by drakewill-CRL** [comment]
Hold off on merging this until I slap together some sprites for the new items

**Comment by drakewill-CRL** [comment]
OK, now its ready to merge

**Review by Stalkeros2 — DISMISSED** [review]
AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

**Review by Stalkeros2 — APPROVED** [review]
i rember :smiley:

**Pull request merged**
