### PR TITLE
adds openspace: allowing multi-z

### PR DESCRIPTION
**Pull request by jjpark-kb**
# What this PR does
title.

# Why it should be added to the game
Multi-Z is a way of adding more space to where it still feels somewhat small.

### CODE REVIEW

**Comment by jjpark-kb** [comment]
this does not have the actual map part. Removed it for the sake of atomization.
I am thinking about how to make a station map with the multiz though.

**Review by BurgerLUA — APPROVED** [review]

**Comment by BurgerLUA** [comment]
Will be merged April 1st.

**Comment by BurgerLUA** [comment]
Couldn't get around to testing this. It's all functional, correct? Just needs to be mapped in?

**Comment by jjpark-kb** [comment]
> Couldn't get around to testing this. It's all functional, correct? Just needs to be mapped in?

yep.

**Pull request merged**
