### PR TITLE
OH GOD OH FUCK OH SHIT

### PR DESCRIPTION
**Pull request by jc-denthead**
# What this PR does
**Untested, webedited..**

Changes a **really bad thing.**

# Why it should be added to the game
I'm not explaining a damn thing.

### CODE REVIEW

**Comment by Stalkeros2** [comment]
(

**Comment by Stalkeros2** [comment]
That's the joke man.

**Comment by DeadliestDesire** [comment]
Cringe and unbased

**Comment by Moltovz** [comment]
Oh shit

**Comment by Moltovz** [comment]
@BurgerLUA merge ASAP or else GitHub is going to eat you

**Comment by Moltovz** [comment]
They are changing the name or anything that calls this dnm until they say

**Comment by jc-denthead** [comment]
Good to merge.

**Comment by jc-denthead** [comment]
Good to merge. Also please for the love of god give this a better name.

**Comment by DeadliestDesire** [comment]
@jc-denthead  small pp energy

**Review by BurgerLUA — APPROVED** [review]
I don't think Github would break out about this since it is a word, but whatever.

**Pull request merged**
