### PR TITLE
revamps the sleeper area

### PR DESCRIPTION
**Pull request by Moltovz**
# What this PR does

revamps the sleeper area

# Why it should be added to the game
less ugliness

### CODE REVIEW

**Comment by Moltovz** [comment]
image

**Comment by Moltovz** [comment]
why conflict

**Comment by Moltovz** [comment]
https://i.imgflip.com/58eyvu.png

**Comment by Moltovz** [comment]
fuck merge conflicts, all my homies hate merge conflicts!!!11!!1!

**Review by Stalkeros2 — APPROVED** [review]
basd

**Pull request merged**
