### PR TITLE
Adds drops to Dick Kickem, new sanity melee weapon and sunglasses reskin.

### PR DESCRIPTION
**Pull request by muzcl**
# What this PR does
Adds a new melee weapon that deals sanity damage, the "Odd Hammer." Rumor has it that Dick kept this secret from everyone except his closest friends (himself), so you'll have to butcher it to get it out of him. You can also get a sunglasses reskin, "douchebag shades." It doesn't have any benefits over actual shades, so its just to steal some of Dick's drip. Due to his overwhelming douchebaggery dripping of him, its pried to his face, and so you'll have to butcher him to get it off him.

# Why it should be added to the game
To my knowledge, we don't have any melee weapons that specialize in sanity currently, and I feel like this is a funny fit that isn't just eldritch horror woah spooky. Dick Kicken needed some drops too, and I feel like these fit pretty well.

### CODE REVIEW

**Comment by muzcl** [comment]
Forgot to show the weapon in its glory:
image
image
image
huge thanks to nzzy on discord, they made the sprites

**Comment by BurgerLUA** [comment]
yeah uhhhhh not sure about adding a dildo hammer as loot as funny as it is

**Comment by Stalkeros2** [comment]
:(

**Comment by muzcl** [comment]
> yeah uhhhhh not sure about adding a dildo hammer as loot as funny as it is

I dont think its that bad, it doesn't explicitly say its a dildo, and it looks like a hammer until someone points it out/you realize with context clues. If you're worried about people ERPing with it, then chances are they would probably ERP anyway without the hammer. Same with people just being weird about it.

If you'd like, I could change the description or sprite around to be less obvious about it. I still think its a good idea, and I don't want nzzy's work to go to waste.

**Comment by BurgerLUA** [comment]
It's too penis like. It'd be fine if it was changed to orange or yellow, like the banhammer, and given less of a cock and balls shape.

**Comment by muzcl** [comment]
> It's too penis like. It'd be fine if it was changed to orange or yellow, like the banhammer, and given less of a cock and balls shape.

I'll do that in a couple weeks, wont be able to access my computer till then.

**Comment by muzcl** [comment]
MUCH better idea for this weapon

**Pull request closed without merging**
